# Generated by Django 5.1.1 on 2024-10-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание задачи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ToDo", "К исполнению"),
                            ("In Progress", "В процессе"),
                            ("Done", "Выполнена"),
                            ("Closed", "Отменена"),
                        ],
                        default="ToDo",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_related",
                    models.BooleanField(
                        default=False, verbose_name="Признак связанной задачи"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Признак активной задачи"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trackers.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
