# Generated by Django 5.1.1 on 2024-10-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0004_task_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="owner",
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_complete",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время выполнения"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trackers.employee",
                        verbose_name="Исполнитель задачи",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trackers.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трек",
                "verbose_name_plural": "Треки",
            },
        ),
    ]
