# Generated by Django 5.1.1 on 2024-10-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0006_rename_owner_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trackers.employee",
                verbose_name="Исполнитель задачи",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="time_complete",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время выполнения"
            ),
        ),
        migrations.DeleteModel(
            name="Tracker",
        ),
    ]
