# Generated by Django 5.1.1 on 2024-10-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0007_remove_task_user_task_executor_task_time_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="trackers.employee",
                verbose_name="Исполнитель задачи",
            ),
        ),
    ]
