# Generated by Django 5.1.1 on 2024-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0011_alter_task_parent_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="patronymic",
        ),
        migrations.AddField(
            model_name="employee",
            name="full_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Фамилия, имя, отчество",
            ),
        ),
    ]
