# Generated by Django 5.1.1 on 2024-10-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trackers",
            "0012_remove_employee_first_name_remove_employee_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trackers.task",
                verbose_name="Родительская задача",
            ),
        ),
    ]
