# Generated by Django 5.1.1 on 2024-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0015_alter_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="chat_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="ID чата Telegram"
            ),
        ),
    ]
