# Generated by Django 5.1.1 on 2024-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0016_employee_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_execution",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начала выполнения"
            ),
        ),
    ]
